function Invoke-UserBackup {
<#
.SYNOPSIS
Creates a user profile focused backup set including browsers, printers, system info,
networking details, installed software, drivers, and more.

.DESCRIPTION
Invoke-UserBackup is the central backup orchestrator for the Maintenance Toolkit.
It supports two modes:

1. Default (ParameterSet: All)
   Runs every available backup routine and writes results to the specified
   backup directory.

2. Selective (ParameterSet: Selective)
   Allows choosing individual backup components such as browsers, printers,
   networking, installed software, drivers, and more.

If the backup directory does not exist, it is created automatically.

.PARAMETER BackupDir
The directory where all backup output will be stored. The folder will be created
if it does not already exist.

.PARAMETER Browsers
Backs up browser‑related data such as bookmarks and profiles.

.PARAMETER Printers
Exports installed printers and print configuration.

.PARAMETER SystemInfo
Collects system information including OS details, hardware, and environment data.

.PARAMETER MappedDrives
Exports mapped network drives.

.PARAMETER Networking
Backs up networking configuration such as IP settings, adapters, and routes.

.PARAMETER InstalledSoftware
Exports installed software inventory.

.PARAMETER WingetCompare
Generates a comparison between installed software and available Winget packages.

.PARAMETER Drivers
Exports installed driver information.

.PARAMETER UserFiles
Back up user files directly to a ZIP archive. Source folders: Desktop, Documents, Downloads, Pictures, Favorites

.INPUTS
The target directory to store all backup data generated by these functions

.Outputs
Backups of user data, configurations, and files

.EXAMPLE
Invoke-UserBackup -BackupDir "C:\Backups\User01"

Runs a full backup using all available backup modules.

.EXAMPLE
Invoke-UserBackup -BackupDir "D:\Backup" -Selective -InstalledSoftware -Networking

Runs only the InstalledSoftware and Networking backup routines.


.NOTES
Author: Shawn Murdock 2026
Part of the Windows Maintenance Toolkit.
Uses multiple internal backup functions such as Backup-BrowserBookmarks,
Backup-Printers, Backup-SystemInfo, Backup-MappedDrives, Backup-Networking,
Backup-InstalledSoftware, Compare-SoftwareWithWinget, and Export-InstalledDrivers.

#>
	[CmdletBinding(DefaultParameterSetName = 'All')]
	[Alias('ddbu')]
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir,

		[Parameter(ParameterSetName = 'Selective')]
		[switch]$Browsers,

		[Parameter(ParameterSetName = 'Selective')]
		[switch]$Printers,

		[Parameter(ParameterSetName = 'Selective')]
		[switch]$SystemInfo,

		[Parameter(ParameterSetName = 'Selective')]
		[switch]$MappedDrives,

		[Parameter(ParameterSetName = 'Selective')]
		[switch]$Networking,

		[Parameter(ParameterSetName = 'Selective')]
		[switch]$InstalledSoftware,

		[Parameter(ParameterSetName = 'Selective')]
		[switch]$WingetCompare,

		[Parameter(ParameterSetName = 'Selective')]
		[switch]$Drivers,

		[Parameter(ParameterSetName = 'Selective')]
		[switch]$UserFiles
	)
	if ($Host.Name -eq 'ConsoleHost') {Clear-Host}
	Write-Host ""
	Write-Host "Backup Started" -ForegroundColor Cyan
	Write-Host "Backup Path: " -ForegroundColor DarkCyan -NoNewline
	Write-Host $BackupDir -ForegroundColor Green
	Write-Host "---------------------------------------------" -ForegroundColor Blue
	if (-not (Test-Path $BackupDir)) {
		New-Item -ItemType Directory -Path $BackupDir -Force | Out-Null
	}
	$runAll = $PSCmdlet.ParameterSetName -eq 'All'
	$results = [System.Collections.Generic.List[psobject]]::new()
	if ($runAll -or $Browsers) {
			$results += Backup-Chromebm -BackupDir $BackupDir
	}
	if ($runAll -or $Browsers) {
			$results += Backup-Vivaldibm -BackupDir $BackupDir
	}
	if ($runAll -or $Browsers) {
			$results += Backup-Operabm -BackupDir $BackupDir
	}
	if ($runAll -or $Browsers) {
			$results += Backup-Firefoxbm -BackupDir $BackupDir
	}
	if ($runAll -or $Browsers) {
			$results += Backup-Edgebm -BackupDir $BackupDir
	}
	if ($runAll -or $Printers) {
			$results += Backup-Printers -BackupDir $BackupDir
	}
	if ($runAll -or $SystemInfo) {
			$results += Backup-SystemInfo -BackupDir $BackupDir
	}
	if ($runAll -or $InstalledSoftware) {
			$results += Backup-InstalledSoftware -BackupDir $BackupDir
	}
	if ($runAll -or $MappedDrives) {
			$results += Backup-MappedDrives -BackupDir $BackupDir
	}
	if ($runAll -or $Networking) {
			$results += Backup-Networking -BackupDir $BackupDir
	}
	if ($runAll -or $Drivers) {
			$results += Export-InstalledDrivers -BackupDir $BackupDir
	}
	if ($runAll -or $UserFiles) {
			$results += Backup-UserFilesCurrentUserToZip -BackupDir $BackupDir
	}
	if ($runAll -or $WingetCompare) {
			$results += Compare-SoftwareWithWinget -BackupDir $BackupDir
	}
	Write-Host ""

	$results | select Section,DurationSec,Success,Errors,FilesCreated | ft -auto

}

Function Invoke-SelectFolder {
	<#
	.SYNOPSIS
		Open select folder dialog
	.DESCRIPTION
		Open select folder dialog
	.NOTES
		Invoke-SelectFolder | Ver. 2.0 | Shawn Murdock | 2022-10-24
	#>
	[CmdletBinding()]
	[alias('selfldr')]
	Param ([string] $initialDirectory)
	Process {
		Add-Type -AssemblyName System.Windows.Forms
		$FolderBrowserDialog = New-Object System.Windows.Forms.FolderBrowserDialog
		$FolderBrowserDialog.RootFolder = 'MyComputer'
		$FolderBrowserDialog.ShowNewFolderButton = $true
		if ($initialDirectory) {
			$FolderBrowserDialog.SelectedPath = $initialDirectory
		}
		[void] $FolderBrowserDialog.ShowDialog()
		return $FolderBrowserDialog.SelectedPath
	}
}

function New-BackupFile {
	param(
		[string]$Name,
		[string]$backupdir,
		[string]$Extension = 'txt'
	)
	join-path $backupdir "\$($env:ComputerName)-$($Name)_$(Get-Date -Format 'yyyyMMdd-HHmmss').$Extension"
}

##
##
##  Browsers
##
##
 function backup-chromebm {
 	[CmdletBinding()]
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir
	)
	Write-Host "Chrome Bookmarks" -ForegroundColor Yellow
	$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	$browserName = 'Chrome'
	$profilename = "Default"
	try {
		if (test-path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe'){
			$bookmarkpath = join-path ($($env:LOCALAPPDATA)) "Google\Chrome\User Data\Default\bookmarks"
			if (test-path $bookmarkpath) {
				$dest = Join-Path $BackupDir ("$($env:COMPUTERNAME)-$browserName-$($profile.Name)-Bookmarks-$(Get-Date -Format 'yyyyMMdd-HHmmss').json")
				Copy-Item $bookmarkPath $dest -Force
				Write-Host "  Backed up $($profileName)" -ForegroundColor Green
				$files += ($bookmarkPath | measure-object).count
			} else { 
				Write-Host "  No bookmarks found" -ForegroundColor DarkCyan
				#continue
			}
		} else {
			Write-Host "  $browserName not installed" -ForegroundColor DarkCyan
			#continue
		}
	} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	#Write-Host "  $browserName bookmarks backed up" -ForegroundColor Green
	return [PSCustomObject]@{
		Section      = $browserName
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}			
 }

function Backup-Vivaldibm {
 	[CmdletBinding()]
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir
	)
	Write-Host "Vivaldi Bookmarks" -ForegroundColor Yellow
	$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	$browserName = 'Vivaldi'
	$profilename = "Default"
	try {
		if (Get-ItemProperty HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Where-Object { $_.DisplayName -like "*Vivaldi*"}) {
			$bookmarkpath = join-path ($($env:LOCALAPPDATA)) "Vivaldi\User Data\Default\bookmarks"
			if (test-path $bookmarkpath) {
				$dest = Join-Path $BackupDir ("$($env:COMPUTERNAME)-$browserName-$($profile.Name)-Bookmarks-$(Get-Date -Format 'yyyyMMdd-HHmmss').json")
				Copy-Item $bookmarkPath $dest -Force
				Write-Host "  Backed up $($profileName)" -ForegroundColor Green
				$files += ($bookmarkPath | measure-object).count
			} else { 
				Write-Host "  No bookmarks found" -ForegroundColor DarkCyan
				#continue
			}
		} else {
			Write-Host "  $browserName not installed" -ForegroundColor DarkCyan
			#continue
		}
	} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	#Write-Host "  $browserName bookmarks backed up" -ForegroundColor Green
	return [PSCustomObject]@{
		Section      = $browserName
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}
}

function Backup-Operabm {
 	[CmdletBinding()]
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir
	)
	Write-Host "Opera Bookmarks" -ForegroundColor Yellow
	$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	$browserName = 'Opera'
	$profilename = "Default"
	try {
		if (Get-ItemProperty HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Where-Object { $_.DisplayName -like "*Opera*" }) {
			$bookmarkpath = join-path ($($env:APPDATA)) "Opera Software\Opera Stable\Default\bookmarks"
			$bookmarkextraspath = join-path ($($env:APPDATA)) "Opera Software\Opera Stable\Default\bookmarksextras"
				if (test-path $bookmarkpath) {
					$dest = Join-Path $BackupDir ("$($env:COMPUTERNAME)-$browserName-$($profile.Name)-Bookmarks-$(Get-Date -Format 'yyyyMMdd-HHmmss').json")
					Copy-Item $bookmarkPath $dest -Force
					Write-Host "  Backed up $($profileName)" -ForegroundColor Green
					$files += ($bookmarkPath | measure-object).count
				} else { 
					Write-Host "  No bookmarks found" -ForegroundColor DarkCyan
					#continue
				}
				if (test-path $bookmarkextraspath) {
					$deste = Join-Path $BackupDir ("$($env:COMPUTERNAME)-$browserName-$($profile.Name)-BookmarksExtras-$(Get-Date -Format 'yyyyMMdd-HHmmss').json")
					Copy-Item $bookmarkPath $deste -Force
					Write-Host "  Backed up $($profileName)" -ForegroundColor Green
					$files += ($bookmarkextraspath | measure-object).count
				} else { 
					Write-Host "  No bookmarks found" -ForegroundColor DarkCyan
					#continue
				}
			} else {
				Write-Host "  $browserName not installed" -ForegroundColor DarkCyan
				#continue
			}
		} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	#Write-Host "  $browserName bookmarks backed up" -ForegroundColor Green
	return [PSCustomObject]@{
		Section      = $browserName
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}
 }

function Backup-Firefoxbm  {
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir
	)
	Write-Host "Firefox Bookmarks" -ForegroundColor Yellow
	$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	$browserName = 'Firefox'
	$profilename = 'Default'
	try {
		if (Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Where-Object { $_.DisplayName -like "*Mozilla Firefox*"}) {
			$ffpath = join-path ($($env:APPDATA)) "Mozilla\Firefox\Profiles\fsopklgz.default-release-1771001168694\bookmarkbackups"
			$bookmarkpath = (Get-ChildItem -path $ffpath | Sort-Object -Property LastWriteTime -Descending | select -First 1).FullName
			if (test-path $bookmarkpath) {
				$dest = Join-Path $BackupDir ("$($env:COMPUTERNAME)-$browserName-$($profile.Name)-Bookmarks-$(Get-Date -Format 'yyyyMMdd-HHmmss').json")
				Copy-Item $bookmarkPath $dest -Force
				Write-Host "  Backed up $($profileName)" -ForegroundColor Green
				$files += ($bookmarkPath | measure-object).count
			} else { 
				Write-Host "  No bookmarks found" -ForegroundColor DarkCyan
				#continue
			}
		} else {
			Write-Host "  $browserName not installed" -ForegroundColor DarkCyan
			#continue
		}
	} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	Write-Host "  Mapped drives exported" -ForegroundColor Green
	return [PSCustomObject]@{
		Section      = $browserName
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}	
}

 function Backup-Edgebm {
 	[CmdletBinding()]
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir
	)
	Write-Host "Edge Bookmarks" -ForegroundColor Yellow
	$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	$browserName = 'Edge'
	$profilename = "Default"
	try {
		if (test-path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe'){
			$bookmarkpath = join-path ($($env:LOCALAPPDATA)) "Google\Chrome\User Data\Default\bookmarks"
			if (test-path $bookmarkpath) {
				$dest = Join-Path $BackupDir ("$($env:COMPUTERNAME)-$browserName-$($profile.Name)-Bookmarks-$(Get-Date -Format 'yyyyMMdd-HHmmss').json")
				Copy-Item $bookmarkPath $dest -Force
				Write-Host "  Backed up $($profileName)" -ForegroundColor Green
				$files += ($bookmarkPath | measure-object).count
			} else { 
				Write-Host "  No bookmarks found" -ForegroundColor DarkCyan
				#continue
			}
		} else {
			Write-Host "  $browserName not installed" -ForegroundColor DarkCyan
			#continue
		}
	} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	Write-Host "  $browserName bookmarks backed up" -ForegroundColor Green
	return [PSCustomObject]@{
		Section      = $browserName
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}			
 }





#$BrowserDefinitions = @{
#	Chrome = @{
#		Type          = 'Chromium'
#		RegistryPath  = 'HKLM:\Software\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe'
#		ProfileRoot   = "$env:LOCALAPPDATA\Google\Chrome\User Data"
#		BookmarkFile  = 'Bookmarks'
#	}
#	Edge = @{
#		Type          = 'Chromium'
#		RegistryPath  = 'HKLM:\Software\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe'
#		ProfileRoot   = "$env:LOCALAPPDATA\Microsoft\Edge\User Data"
#		BookmarkFile  = 'Bookmarks'
#	}
#	Brave = @{
#		Type          = 'Chromium'
#		RegistryPath  = 'HKLM:\Software\Microsoft\Windows\CurrentVersion\App Paths\brave.exe'
#		ProfileRoot   = "$env:LOCALAPPDATA\BraveSoftware\Brave-Browser\User Data"
#		BookmarkFile  = 'Bookmarks'
#	}
#	Firefox = @{
#		Type         = 'Firefox'
#		RegistryPath = 'HKLM:\Software\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe'
#		ProfileRoot  = "$env:APPDATA\Mozilla\Firefox\Profiles"
#		PlacesFile   = 'places.sqlite'
#	}
#	Opera = @{
#		Type         = 'Chromium'
#		RegistryPath = 'HKCU:\Software\Opera Software'
#		ProfileRoot  = "$env:APPDATA\Opera Software"
#		BookmarkFile = 'Bookmarks'
#	}
#	Vivaldi = @{
#		Type         = 'Chromium'
#		RegistryPath = 'HKCU:\Software\Vivaldi'
#		ProfileRoot  = "$env:LOCALAPPDATA\Vivaldi\User Data"
#		BookmarkFile = 'Bookmarks'
#	}
#}
#
#function Test-BrowserInstalled {
#	param ([string]$RegistryPath)
#	try {
#		if (-not (Test-Path $RegistryPath)) { return $false }
#		$exe = (Get-ItemProperty $RegistryPath).'(Default)'
#		return $exe -and (Test-Path $exe)
#	}
#	catch { return $false }
#}
#
#function Get-BrowserProfiles {
#	param (
#		[Parameter(Mandatory)]
#		[string]$ProfileRoot
#	)
#	if (-not (Test-Path $ProfileRoot)) { return @() }
#	Get-ChildItem -Path $ProfileRoot -Directory -ErrorAction SilentlyContinue |
#		Where-Object { $_.Name -match 'Default|Profile|Stable' }
#}
#
#function Backup-BrowserBookmarks {
#	param (
#		[Parameter(Mandatory)]
#		[string]$BackupDir,
#
#		[hashtable]$BrowserTable = $BrowserDefinitions
#	)
#	Write-Host "Browser Bookmarks Backup" -ForegroundColor Yellow
#	foreach ($browserName in $BrowserTable.Keys) {
#		$browser = $BrowserTable[$browserName]
#		if (-not (Test-BrowserInstalled -RegistryPath $browser.RegistryPath)) {
#			Write-Host "  $browserName not installed" -ForegroundColor DarkCyan
#			continue
#		}
#		Write-Host "  Processing $browserName" -ForegroundColor Cyan
#		$profiles = Get-BrowserProfiles -ProfileRoot $browser.ProfileRoot
#		if (-not $profiles) {
#			Write-Host "    No profiles found" -ForegroundColor DarkYellow
#			continue
#		}
#		foreach ($profile in $profiles) {
#			switch ($browser.Type) {
#				'Chromium' {
#					$bookmarkPath = Join-Path $profile.FullName $browser.BookmarkFile
#					if (Test-Path $bookmarkPath) {
#						$dest = Join-Path $BackupDir (
#							"$($env:COMPUTERNAME)-$browserName-$($profile.Name)-Bookmarks-$(Get-Date -Format 'yyyyMMdd-HHmmss').json"
#						)
#						Copy-Item $bookmarkPath $dest -Force
#						Write-Host "    Backed up $($profile.Name)" -ForegroundColor Green
#					}
#				}
#				'Firefox' {
#					if (Get-Process firefox -ErrorAction SilentlyContinue) {
#						Write-Warning "Firefox is running; bookmark backup may be inconsistent"
#					}
#					$places = Join-Path $profile.FullName $browser.PlacesFile
#					if (Test-Path $places) {
#						$dest = Join-Path $BackupDir (
#							"$($env:COMPUTERNAME)-Firefox-$($profile.Name)-Bookmarks-$(Get-Date -Format 'yyyyMMdd-HHmmss').sqlite"
#						)
#						Copy-Item $places $dest -Force
#						Write-Host "    Backed up $($profile.Name)" -ForegroundColor Green
#					}
#				}
#			}
#		}
#	}
#}


##
##
## Printer
##
##
function Test-RealPrinter {
	param ($Printer)
	if (-not $Printer.PortName) { return $false }
	# Exclude known virtual ports
	if ($Printer.PortName -match '^(PORTPROMPT:|FILE:|nul|XPS|PDF)' ) {
		return $false
	}
	# Exclude known virtual drivers
	if ($Printer.DriverName -match 'Microsoft|OneNote|PDF|XPS|Fax') {
		return $false
	}
	return $true
}

function Backup-Printers {
	[CmdletBinding()]
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir
	)
	Write-Host "Printers Export" -ForegroundColor Yellow
	$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	try {
		$printers = Get-Printer -ErrorAction Stop |
		Where-Object { Test-RealPrinter $_ } |
			Select-Object `
				Name,
				DriverName,
				PortName,
				ShareName,
				Shared,
				Published,
				ComputerName,
				@{ Name = 'IsDefault'; Expression = { $_.Name -eq (Get-Printer | Where-Object Default).Name } }
		if (-not $printers) {
			Write-Host "  No printers found" -ForegroundColor DarkYellow
			$end = Get-Date
			return [PSCustomObject]@{
				Section      = 'Printers'
				StartTime    = $start
				EndTime      = $end
				DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
				Success      = $success
				FilesCreated = 0
				Errors       = "No printers found"
			}
		}
		$csvPath = New-BackupFile -Name "Printers" -Extension csv -backupdir $BackupDir
		$txtPath = New-BackupFile -Name "Printers" -Extension txt -backupdir $BackupDir
		$printers | Export-Csv -Path $csvPath -NoTypeInformation
		$files += ($csvPath | measure-object).count
		$printers | Format-Table -AutoSize | Out-File $txtPath
		$files += ($txtPath | measure-object).count
		Write-Host "  Printers exported (CSV + TXT)" -ForegroundColor Green
	} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	return [PSCustomObject]@{
		Section      = 'Printers'
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}
}



##
##
## Mapped Drives
##
##
function Test-RestorableMappedDrive {
	param ($Drive)
	if (-not $Drive.ProviderName) { return $false }
	if ($Drive.ProviderName -notmatch '^\\\\') { return $false }
	if (-not $Drive.Name) { return $false }
	return $true
}

function Backup-MappedDrives {
	[CmdletBinding()]
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir
	)
	$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	Write-Host "Mapped Drive Export" -ForegroundColor Yellow
	try {
		# Active mappings
		$active = Get-CimInstance Win32_MappedLogicalDisk |
			Where-Object { Test-RestorableMappedDrive $_ } |
			Select-Object Name, ProviderName
		# Persistent mappings (HKCU)
		$persistent = Get-ItemProperty 'HKCU:\Network\*' -ErrorAction SilentlyContinue |
			Select-Object `
				@{ Name='Name'; Expression={ $_.PSChildName } },
				@{ Name='ProviderName'; Expression={ $_.RemotePath } }
		$drives = ($active + $persistent) |
			Sort-Object Name, ProviderName -Unique
		if (-not $drives) {
			Write-Host "  No mapped drives found" -ForegroundColor DarkYellow
			return
		}
			$drvsfile = New-BackupFile -Name "MappedDrives" -Extension csv -backupdir $BackupDir
			$drives | Export-Csv $drvsfile -NoTypeInformation
			$files += ($drvsfile | measure-object).count
	} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	Write-Host "  Mapped drives exported" -ForegroundColor Green
	return [PSCustomObject]@{
		Section      = 'DrvMappings'
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}	
}


##
##
## Network
##
##
function Backup-Networking {
	[CmdletBinding()]
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir
	)
	$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	try {
		if (-not (Test-Path $BackupDir)) {
			New-Item -ItemType Directory -Path $BackupDir -Force -ErrorAction Stop | Out-Null
		}
		$NetConfig = New-BackupFile -Name "Netconfig" -Extension xml -BackupDir $BackupDir
		$NICCfg    = New-BackupFile -Name "NetAdapter" -Extension csv -BackupDir $BackupDir
		$Routes    = New-BackupFile -Name "Routing" -Extension csv -BackupDir $BackupDir
		$IPConfig  = New-BackupFile -Name "IPConfig" -Extension txt -BackupDir $BackupDir
		Get-NetIPConfiguration -ErrorAction Stop | Export-Clixml $NetConfig
		$files += ($NetConfig | measure-object).count
		Get-NetAdapter -ErrorAction Stop |
			Select InterfaceDescription,MacAddress,Status,LinkSpeed,FullDuplex,
				   DriverDescription,DriverVersionString |
			Export-Csv $NICCfg -NoTypeInformation
		$files += ($NICCfg | measure-object).count
		Get-NetRoute -ErrorAction Stop |
			Export-Csv $Routes -NoTypeInformation
		$files += ($Routes | measure-object).count
		ipconfig /all | Out-File $IPConfig -Encoding UTF8
		$files += ($IPConfig | measure-object).count
	} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	Write-Host "  Mapped drives exported" -ForegroundColor Green
	return [PSCustomObject]@{
		Section      = 'Networking'
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}
}

##
##
## System Info
##
##
function Backup-SystemInfo {
	[CmdletBinding()]
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir
	)
	$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	Write-Host "System Information Capture" -ForegroundColor Yellow
	try {
		$Sysnfo = New-BackupFile -Name "SystemInfo" -Extension txt -backupdir $BackupDir
		$obj = systeminfo /FO CSV | ConvertFrom-Csv
		$obj | Format-List | out-file $Sysnfo
		$files += ($sysnfo | measure-object).count
	} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	Write-Host "  System information exported" -ForegroundColor Green
	return [PSCustomObject]@{
		Section      = 'SysInfo'
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}
}


##
##
## Software
##
##
function Get-InstalledSoftware {
	[CmdletBinding()]
	param ()
	$SWList = Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',
	'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*',
	'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*'
	$swlist |
	ForEach-Object {
		[PSCustomObject]@{
			DisplayName      = $_.DisplayName
			DisplayVersion   = $_.DisplayVersion
			Publisher        = $_.Publisher
			InstallDate      = $_.InstallDate
			InstallLocation  = $_.InstallLocation
			UninstallString  = $_.UninstallString
			WindowsInstaller = $_.WindowsInstaller
			HelpLink         = $_.HelpLink
			EstimatedSize    = $_.EstimatedSize
#			InstallSource    = $_.InstallSource
#			Scope            = $key.Scope
#			Architecture     = $key.Arch
#			RegistryPath     = $_.PSPath
		}
	}
}

function Backup-InstalledSoftware {
	[CmdletBinding()]
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir
	)
	$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	Write-Host "Installed Software Inventory" -ForegroundColor Yellow
	try {
		$software = Get-InstalledSoftware | Sort-Object DisplayName
		if (-not $software) {
			Write-Host "  No software entries found" -ForegroundColor DarkYellow
			return
		}
		$Softcsv = New-BackupFile -Name "InstalledSoftware" -Extension csv -backupdir $BackupDir
		$Softjsono = New-BackupFile -Name "InstalledSoftware" -Extension json -backupdir $BackupDir
		$software | Export-Csv  $Softcsv -NoTypeInformation
		$files += ($Softcsv | measure-object).count
		$software | ConvertTo-Json -Depth 4 | Out-File $Softjsono -Encoding UTF8
		$files += ($Softjsono | measure-object).count
	} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	Write-Host "  Software inventory exported" -ForegroundColor Green
	return [PSCustomObject]@{
		Section      = 'Software'
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}
}

function Compare-SoftwareWithWinget {
	[CmdletBinding()]
	param (		
		[Parameter(Mandatory)]
		[string]$BackupDir
	)
	$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	try {
		if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
			Write-Warning "Winget not available"
			return
		}
		$SoftwareInfoCSV = Get-ChildItem $BackupDir -Filter "$($env:COMPUTERNAME)-InstalledSoftware_*.csv" |
			Sort-Object LastWriteTime -Descending | Select-Object -First 1
		if (-not $SoftwareInfoCSV) {
			Write-Warning "No InstalledSoftware CSV found for Winget comparison"
			return
		} else {
			$software = Import-Csv $SoftwareInfoCSV
		}
		$winget   = winget list --accept-source-agreements --disable-interactivity |
					Select-Object -Skip 1
		$matches = foreach ($app in $software) {
			if ($winget -match [regex]::Escape($app.DisplayName)) {
				[PSCustomObject]@{
					DisplayName = $app.DisplayName
					Publisher   = $app.Publisher
	#				Scope       = $app.Scope
					WingetMatch = $true
				}
			}
		}
		if ($matches) {
			$WingetSoft = New-BackupFile -Name "WingetMatches" -Extension csv -backupdir $BackupDir
			$matches | Export-Csv $WingetSoft -NoTypeInformation
			$files += ($WingetSoft | measure-object).count
			Write-Host "  Winget correlation saved" -ForegroundColor Green
		}
	} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	return [PSCustomObject]@{
		Section      = 'WingetCorr'
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}
}


##
##
## User Files
##
##
function Backup-UserFilesCurrentUserToZip {
	[CmdletBinding()]
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir,

		[Parameter()]
		[string]$ZipName = 'UserFiles.zip'
	)
		$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	Write-Host "User Files Backup (Current User)" -ForegroundColor Yellow
	try {
		$zipPath = Join-Path $BackupDir $ZipName
		Remove-Item $zipPath -Force -ErrorAction SilentlyContinue
		$shell = New-Object -ComObject Shell.Application
		$knownFolders = @{
			Desktop    = [Environment]::GetFolderPath('Desktop')
			Documents  = [Environment]::GetFolderPath('MyDocuments')
			Downloads  = $shell.NameSpace('shell:Downloads').Self.Path
			Pictures   = [Environment]::GetFolderPath('MyPictures')
			Favorites  = [Environment]::GetFolderPath('Favorites')
		}
		$pathsToZip = @()
		foreach ($folder in $knownFolders.GetEnumerator()) {
			if ($folder.Value -and (Test-Path $folder.Value)) {
				Write-Host "  Queued: $($folder.Key) -> $($folder.Value)" -ForegroundColor Cyan
				$pathsToZip += $folder.Value
			} else {
				Write-Host "  Skipped: $($folder.Key) (not present)" -ForegroundColor DarkYellow
			}
		}
		if (-not $pathsToZip) {
			Write-Warning "No user folders found to back up"
			return
		}
		Write-Host "Creating ZIP archive..." -ForegroundColor Yellow
		foreach ($path in $pathsToZip) {
			Compress-Archive -Path $path -DestinationPath $zipPath -Update -ErrorAction Stop
			$files += ($path | measure-object).count
		}
	} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	Write-Host "  Backup complete: $zipPath" -ForegroundColor Green
	return [PSCustomObject]@{
		Section      = 'UserData'
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}
}



##
##
## Drivers
##
##
function Get-InstalledDrivers {
	[CmdletBinding()]
	param (
		[string[]]$ExcludeManufacturer = @('Microsoft')
	)
	Get-CimInstance Win32_PnPSignedDriver |
		Where-Object {
			$_.DeviceName -and
			$_.DriverVersion -and
			$_.InfName -and
			($ExcludeManufacturer -notcontains $_.Manufacturer)
		} |
		Select-Object `
			DeviceName,
			Manufacturer,
			DriverVersion,
			DriverDate,
			InfName,
			DriverProviderName,
			IsSigned,
			FriendlyName,
			HardwareID
}

function Export-InstalledDrivers {
	[CmdletBinding()]
	param (
		[Parameter(Mandatory)]
		[string]$BackupDir
	)
	$start   = Get-Date
	$errors  = @()
	$files   = @()
	$success = $true
	Write-Host "Installed Driver Capture" -ForegroundColor Yellow
	try {
		$txtFile = New-BackupFile -Name "DriversInfo" -Extension txt -backupdir $BackupDir
		$csvFile = New-BackupFile -Name "DriversInfo" -Extension csv -backupdir $BackupDir
		$drivers = Get-InstalledDrivers
		if (-not $drivers) {
			Write-Warning "No drivers found"
			return
		}
		$drivers |
			Sort-Object Manufacturer, DeviceName |
			Format-Table Devicename,Manufacturer,FriendlyName,DriverVersion,DriverDate,InfName -AutoSize | Out-File $txtFile
		$files += ($txtFile | measure-object).count
		$drivers |
			Sort-Object Manufacturer, DeviceName | Export-Csv $csvFile -NoTypeInformation
		$files += ($csvFile | measure-object).count
	} catch {
		$success = $false
		$errors += $_.Exception.Message
	}
	$end = Get-Date
	Write-Host "  Driver list saved" -ForegroundColor Green
	return [PSCustomObject]@{
		Section      = 'Drivers'
		StartTime    = $start
		EndTime      = $end
		DurationSec  = [math]::Round(($end - $start).TotalSeconds,2)
		Success      = $success
		FilesCreated = ($files).count
		Errors       = $errors
	}
}

